### PR TITLE
Finish

### PR DESCRIPTION
**Pull request by archer31**
PocketTA
timeslots choices
4,5,6,3,2,1

### CODE REVIEW

**Comment by kbuffardi** [comment]
Close! But in your implementation, the View is coupled to the Model. We want to keep the Model decoupled from the View so neither is directly dependent on the other's implementation.

Also, when each instance of a view has its own model, the data persistence within the model is lost.

**Comment by archer31** [comment]
are we allowed to change the observer classes in order to allow us to pass arguments through `notifyObservers()` and then through `update()`?

**Comment by kbuffardi** [comment]
It should be possible without changing the ObserverPattern.hpp file at all. If you look at the example (AnInt model, with controller and two views), you should be able to replicate something similar for SmarTrafficMVP

**Comment by SpaceManiac** [comment]
I find some documentation indicating that a view is allowed to reference a model type, such as Figures 3 and 4 on [this MSDN doc](https://msdn.microsoft.com/en-us/library/ff649643.aspx). Notably, the model and view remain decoupled, such that the model need not know about the view. I also worry that with the Controller being the `IObserver`, there is no way to differentiate which model has changed, and therefore all views must be pinged for updates whether they have changed or not; some stateful intermediate type is required to avoid this.

Nonetheless, I or one of my team members shall amend this PR with the change you suggest.

**Comment by kbuffardi** [comment]
Right, there are some variations of MVC that allow for direct communication from the model to the view. Technically, I believe the original MVC takes this approach, but often using the controller as a "middle-man" enables us to have looser overall coupling.

If the observer pattern interface has an update() function that allows for parameters, it would be simpler to identify which model has updated. Some [Observer Pattern libraries do this such as using pseudo-generic types like Java's *Object*](https://docs.oracle.com/javase/7/docs/api/java/util/Observer.html), from which all classes inherit. However, it is not as elegant to implement it this way in C++ due to the way the language was designed. Consequently, implementing the Observer Pattern in C++ has no perfectly clean design and we then settle by accepting a limitation, such as `update` being incapable of differentiating between multiple *subjects* being observed. 

In this specific application, the catch is that we can either accept redundant view updates by observing both instance variables (that comprise the *model*), or we can only observe one and update both with the assumption that when one updates that both are going to have updating data. You have to be careful of race conditions and this approach resembles something similar to the [Sequential coupling anti-pattern](https://en.wikipedia.org/wiki/Sequential_coupling) (i.e. a design pattern to avoid) but, this is the limitation of our approach to Observer Pattern.

This is a long-winded response, but you brought up very good points so I wanted to shed some light on the reasoning. There's a better implementation even sticking to this Observer Pattern library, but involves a more complicated model. If I have time after catching up on grading/feedback/etc, I'll post this better implementation as a branch and share it with the class.

**Comment by SpaceManiac** [comment]
The PR has been updated.

Thank you for taking the time to reply in detail, it's been informative. One idea for working around C++'s lack of `Object` - which might be inelegant for certain situations, admittedly - is to parameterize `IObserver` and `Observable` on the message type. It would mean having to deal with templates, which might be unfun, but *would* be typesafe. Roughly.

I chose the sequential ordering in this update, because the redundant prints were more annoying than the two-line swap needed to make things work in this situation. I can certainly see it causing subtle bugs down the road.

**Pull request closed without merging**
